# Generated by Django 4.2.16 on 2024-11-08 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("topic", models.TextField()),
                ("purpose", models.TextField()),
                ("last_update_ts", models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SlackUser",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("real_name", models.TextField()),
                ("email", models.TextField()),
                ("image_48", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ChannelPartialUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oldest_message_ts", models.CharField(max_length=32, null=True)),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="slack.channel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_ts", models.CharField(max_length=32)),
                ("last_update_ts", models.CharField(max_length=32)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="slack.channel"
                    ),
                ),
            ],
            options={
                "unique_together": {("channel", "thread_ts")},
            },
        ),
        migrations.CreateModel(
            name="SlackActivityBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("count", models.PositiveIntegerField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="slack.channel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="slack.slackuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("channel", "day", "user")},
            },
        ),
    ]
