# Generated by Django 4.2.16 on 2024-11-08 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0002_channelupdategap_delete_channelpartialupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeenMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.CharField(max_length=32)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="slack.channel"
                    ),
                ),
            ],
            options={
                "unique_together": {("channel", "ts")},
            },
        ),
    ]
