# Generated by Django 4.2.16 on 2024-11-08 22:57

from django.db import migrations, models
import django.db.models.functions.comparison
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0003_seenmessage"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="channelupdategap",
            constraint=models.CheckConstraint(
                check=django.db.models.lookups.GreaterThan(
                    django.db.models.functions.comparison.Cast(
                        "newest_message_ts", output_field=models.FloatField()
                    ),
                    django.db.models.functions.comparison.Cast(
                        "oldest_message_ts", output_field=models.FloatField()
                    ),
                ),
                name="newest_newer_than_oldest",
            ),
        ),
    ]
