# Generated by Django 4.2.16 on 2024-11-08 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0004_channelupdategap_newest_newer_than_oldest"),
    ]

    operations = [
        migrations.AddField(
            model_name="seenmessage",
            name="thread",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="slack.thread",
            ),
        ),
    ]
