# Generated by Django 4.2.16 on 2024-11-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0005_seenmessage_thread"),
    ]

    operations = [
        migrations.AddField(
            model_name="seenmessage",
            name="db_created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thread",
            name="db_created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
