# Generated by Django 4.2.16 on 2024-11-09 01:00

from django.db import migrations, models
import django.db.models.functions.comparison
import django.db.models.lookups


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0006_seenmessage_db_created_at_thread_db_created_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.CheckConstraint(
                check=django.db.models.lookups.GreaterThanOrEqual(
                    django.db.models.functions.comparison.Cast(
                        "last_update_ts", output_field=models.FloatField()
                    ),
                    django.db.models.functions.comparison.Cast(
                        "thread_ts", output_field=models.FloatField()
                    ),
                ),
                name="update_newer_than_created",
            ),
        ),
    ]
