# Generated by Django 4.2.16 on 2024-11-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0007_thread_update_newer_than_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="last_update_ts",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
